version: '3.8'

services:
  backend:
    build: ./backend
    container_name: django_app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
    restart: always

  frontend:
    build: ./frontend
    container_name: react_app
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: always